"""Writes .env and config/user_profile.py from wizard-collected data."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)


def write_env_file(project_root: Path, config: dict[str, Any]) -> Path:
    """Write .env file from collected configuration. Returns the path."""
    env_path = project_root / ".env"

    lines = [
        "# =============================================================================",
        "# DoNotes Configuration (generated by Setup Wizard)",
        "# =============================================================================",
        "",
        "# --- Telegram Bot ---",
        f"DONOTES_TELEGRAM_BOT_TOKEN={config['telegram_bot_token']}",
        f"DONOTES_TELEGRAM_ALLOWED_USER_IDS=[{config['telegram_user_id']}]",
        "",
        "# --- OpenAI ---",
        f"DONOTES_OPENAI_API_KEY={config['openai_api_key']}",
        f"DONOTES_OPENAI_MODEL={config.get('openai_model', 'gpt-4o')}",
        "",
        "# --- Google APIs ---",
        "DONOTES_GOOGLE_CREDENTIALS_PATH=data/google_tokens/credentials.json",
        "DONOTES_GOOGLE_TOKEN_PATH=data/google_tokens/token.json",
        f"DONOTES_GMAIL_SENDER_EMAIL={config['gmail_sender_email']}",
        f"DONOTES_GMAIL_RECIPIENT_EMAIL={config.get('gmail_recipient_email', config['gmail_sender_email'])}",
        f"DONOTES_WORK_CALENDAR_ID={config.get('work_calendar_id', config['gmail_sender_email'])}",
        f"DONOTES_PERSONAL_CALENDAR_ID={config.get('personal_calendar_id', config['gmail_sender_email'])}",
        "",
        "# --- Google Sheets (auto-populated on first run) ---",
        "DONOTES_GOOGLE_SHEET_ID=",
        "",
        "# --- User ---",
        f"DONOTES_TIMEZONE={config.get('timezone', 'UTC')}",
        f"DONOTES_USER_NAME={config.get('user_name', '')}",
        "",
        "# --- Whisper ---",
        f"DONOTES_WHISPER_MODEL={config.get('whisper_model', 'distil-large-v3')}",
        f"DONOTES_WHISPER_BATCH_SIZE={config.get('whisper_batch_size', '12')}",
        "",
        "# --- Morning Brief ---",
        f"DONOTES_MORNING_BRIEF_HOUR={config.get('morning_brief_hour', '8')}",
        f"DONOTES_MORNING_BRIEF_MINUTE={config.get('morning_brief_minute', '0')}",
        f"DONOTES_WEEKLY_DIGEST_DAY={config.get('weekly_digest_day', 'monday')}",
        f"DONOTES_WEEKLY_DIGEST_HOUR={config.get('weekly_digest_hour', '9')}",
    ]

    env_path.write_text("\n".join(lines) + "\n")
    log.info("Wrote .env to %s", env_path)
    return env_path


def write_user_profile(project_root: Path, config: dict[str, Any]) -> Path:
    """Write config/user_profile.py from personalization data. Returns the path."""
    profile_path = project_root / "config" / "user_profile.py"

    user_name = config.get("user_name", "")
    profile_context = config.get("user_profile_context", "")
    self_names = config.get("self_names", [])
    known_people = config.get("known_people", [])
    whisper_places = config.get("whisper_places", [])
    whisper_companies = config.get("whisper_companies", [])

    # Build self-names set: always include common defaults
    name_set = {"me", "myself", "i"}
    if user_name:
        name_set.add(user_name.lower().split()[0])
    for n in self_names:
        if n.strip():
            name_set.add(n.strip().lower())

    lines = [
        '"""User profile for AI personalization (generated by Setup Wizard)."""',
        "",
        f'USER_NAME = "{user_name}"',
        "",
    ]

    if profile_context:
        escaped = profile_context.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'USER_PROFILE_CONTEXT = """\\\n{escaped}\n"""')
    else:
        lines.append('USER_PROFILE_CONTEXT = ""')

    lines += [
        "",
        f"SELF_NAMES = {name_set!r}",
        "",
        f"KNOWN_PEOPLE = {known_people!r}",
        "",
        f"WHISPER_PLACES = {whisper_places!r}",
        "",
        f"WHISPER_COMPANIES = {whisper_companies!r}",
        "",
        "WHISPER_NAMES = []",
        "",
        "GPT_PLACE_CONTEXT = {}",
        "",
        "GPT_COMPANY_CONTEXT = {}",
    ]

    profile_path.write_text("\n".join(lines) + "\n")
    log.info("Wrote user_profile.py to %s", profile_path)
    return profile_path
